.class public final Lddt;
.super Lcpx;


# annotations
.annotation system Ldalvik/annotation/Signature;
    value = {
        "<R::",
        "Lcqg;",
        ">",
        "Lcpx",
        "<TR;>;"
    }
.end annotation


# instance fields
.field private final a:Ldat;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ldat",
            "<TR;>;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>(Lcpy;)V
    .locals 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lcpy",
            "<TR;>;)V"
        }
    .end annotation

    invoke-direct {p0}, Lcpx;-><init>()V

    instance-of v0, p1, Ldat;

    if-nez v0, :cond_0

    new-instance v0, Ljava/lang/IllegalArgumentException;

    const-string v1, "OptionalPendingResult can only wrap PendingResults generated by an API call."

    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v0

    :cond_0
    check-cast p1, Ldat;

    iput-object p1, p0, Lddt;->a:Ldat;

    return-void
.end method


# virtual methods
.method public a(JLjava/util/concurrent/TimeUnit;)Lcqg;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(J",
            "Ljava/util/concurrent/TimeUnit;",
            ")TR;"
        }
    .end annotation

    iget-object v0, p0, Lddt;->a:Ldat;

    invoke-virtual {v0, p1, p2, p3}, Ldat;->a(JLjava/util/concurrent/TimeUnit;)Lcqg;

    move-result-object v0

    return-object v0
.end method

.method public a(Lcqj;)Lcqk;
    .locals 1
    .param p1    # Lcqj;
        .annotation build Landroid/support/annotation/NonNull;
        .end annotation
    .end param
    .annotation build Landroid/support/annotation/NonNull;
    .end annotation

    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<S::",
            "Lcqg;",
            ">(",
            "Lcqj",
            "<-TR;+TS;>;)",
            "Lcqk",
            "<TS;>;"
        }
    .end annotation

    iget-object v0, p0, Lddt;->a:Ldat;

    invoke-virtual {v0, p1}, Ldat;->a(Lcqj;)Lcqk;

    move-result-object v0

    return-object v0
.end method

.method public a()V
    .locals 1

    iget-object v0, p0, Lddt;->a:Ldat;

    invoke-virtual {v0}, Ldat;->a()V

    return-void
.end method

.method public a(Lcpz;)V
    .locals 1

    iget-object v0, p0, Lddt;->a:Ldat;

    invoke-virtual {v0, p1}, Ldat;->a(Lcpz;)V

    return-void
.end method

.method public a(Lcqh;)V
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lcqh",
            "<-TR;>;)V"
        }
    .end annotation

    iget-object v0, p0, Lddt;->a:Ldat;

    invoke-virtual {v0, p1}, Ldat;->a(Lcqh;)V

    return-void
.end method

.method public a(Lcqh;JLjava/util/concurrent/TimeUnit;)V
    .locals 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lcqh",
            "<-TR;>;J",
            "Ljava/util/concurrent/TimeUnit;",
            ")V"
        }
    .end annotation

    iget-object v0, p0, Lddt;->a:Ldat;

    invoke-virtual {v0, p1, p2, p3, p4}, Ldat;->a(Lcqh;JLjava/util/concurrent/TimeUnit;)V

    return-void
.end method

.method public b()Z
    .locals 1

    iget-object v0, p0, Lddt;->a:Ldat;

    invoke-virtual {v0}, Ldat;->g()Z

    move-result v0

    return v0
.end method

.method public c()Lcqg;
    .locals 3
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()TR;"
        }
    .end annotation

    invoke-virtual {p0}, Lddt;->b()Z

    move-result v0

    if-eqz v0, :cond_0

    const-wide/16 v0, 0x0

    sget-object v2, Ljava/util/concurrent/TimeUnit;->MILLISECONDS:Ljava/util/concurrent/TimeUnit;

    invoke-virtual {p0, v0, v1, v2}, Lddt;->a(JLjava/util/concurrent/TimeUnit;)Lcqg;

    move-result-object v0

    return-object v0

    :cond_0
    new-instance v0, Ljava/lang/IllegalStateException;

    const-string v1, "Result is not available. Check that isDone() returns true before calling get()."

    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw v0
.end method

.method public d()Lcqg;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()TR;"
        }
    .end annotation

    iget-object v0, p0, Lddt;->a:Ldat;

    invoke-virtual {v0}, Ldat;->d()Lcqg;

    move-result-object v0

    return-object v0
.end method

.method public e()Z
    .locals 1

    iget-object v0, p0, Lddt;->a:Ldat;

    invoke-virtual {v0}, Ldat;->e()Z

    move-result v0

    return v0
.end method

.method public f()Ljava/lang/Integer;
    .locals 1

    iget-object v0, p0, Lddt;->a:Ldat;

    invoke-virtual {v0}, Ldat;->f()Ljava/lang/Integer;

    move-result-object v0

    return-object v0
.end method
