package com.ca.mdo;

public enum CaMDOError {
  CAMDO_INVALID_DATALENGTH_ERROR_CODE,
  CAMDO_INVALID_PARAMETER_ERROR_CODE,
  CAMDO_JSON_PARSE_ERROR_CODE,
  CAMDO_LOG_INITIALIZE_ERROR_CODE,
  CAMDO_LOG_NETWORKMETRIC_ERROR_CODE,
  CAMDO_LOG_NUMERICMETRIC_ERROR_CODE,
  CAMDO_LOG_SENDSCREENSHOT_ERROR_CODE,
  CAMDO_LOG_TEXTMETRIC_ERROR_CODE,
  CAMDO_POLICY_NOT_APPLIED_ERROR_CODE,
  CAMDO_START_TRANSACTION_FAILED_ERROR_CODE,
  CAMDO_STOP_TRANSACTION_FAILED_ERROR_CODE,
  CAMDO_TRANSACTION_NOT_PRESENT_ERROR_CODE,
  CAMDO_UNKNOWN_ERROR_CODE(2100, "Unknown Error"),
  CAMDO_UPLOAD_ERROR_CODE(2100, "Unknown Error"),
  CAMDO_UPLOAD_INPROGRESS_ERROR_CODE(2100, "Unknown Error"),
  CAMDO_UPLOAD_NOT_OPTED_ERROR_CODE(2100, "Unknown Error"),
  CAMDO_UPLOAD_PERMISSION_DENIED_ERROR_CODE(2100, "Unknown Error"),
  CAMDO_UPLOAD_WIFI_DISABLED_ERROR_CODE(2100, "Unknown Error");
  
  private final int code;
  
  private final String message;
  
  static {
    CAMDO_INVALID_PARAMETER_ERROR_CODE = new CaMDOError("CAMDO_INVALID_PARAMETER_ERROR_CODE", 1, 2101, "Invalid parameters");
    CAMDO_LOG_INITIALIZE_ERROR_CODE = new CaMDOError("CAMDO_LOG_INITIALIZE_ERROR_CODE", 2, 2102, "Initialize Error");
    CAMDO_LOG_TEXTMETRIC_ERROR_CODE = new CaMDOError("CAMDO_LOG_TEXTMETRIC_ERROR_CODE", 3, 2103, "Text Metric Error");
    CAMDO_LOG_NUMERICMETRIC_ERROR_CODE = new CaMDOError("CAMDO_LOG_NUMERICMETRIC_ERROR_CODE", 4, 2104, "Numeric Metric Error");
    CAMDO_LOG_NETWORKMETRIC_ERROR_CODE = new CaMDOError("CAMDO_LOG_NETWORKMETRIC_ERROR_CODE", 5, 2105, "Network Error");
    CAMDO_LOG_SENDSCREENSHOT_ERROR_CODE = new CaMDOError("CAMDO_LOG_SENDSCREENSHOT_ERROR_CODE", 6, 2106, "Send Screenshot Error");
    CAMDO_START_TRANSACTION_FAILED_ERROR_CODE = new CaMDOError("CAMDO_START_TRANSACTION_FAILED_ERROR_CODE", 7, 2107, "Start transaction failed error");
    CAMDO_STOP_TRANSACTION_FAILED_ERROR_CODE = new CaMDOError("CAMDO_STOP_TRANSACTION_FAILED_ERROR_CODE", 8, 2108, "Stop transaction failed error");
    CAMDO_UPLOAD_ERROR_CODE = new CaMDOError("CAMDO_UPLOAD_ERROR_CODE", 9, 2109, "Failed to Upload data");
    CAMDO_UPLOAD_WIFI_DISABLED_ERROR_CODE = new CaMDOError("CAMDO_UPLOAD_WIFI_DISABLED_ERROR_CODE", 10, 2110, "Wifi is not enabled for the Upload");
    CAMDO_UPLOAD_PERMISSION_DENIED_ERROR_CODE = new CaMDOError("CAMDO_UPLOAD_PERMISSION_DENIED_ERROR_CODE", 11, 2111, "Upload Permission Denied.");
    CAMDO_POLICY_NOT_APPLIED_ERROR_CODE = new CaMDOError("CAMDO_POLICY_NOT_APPLIED_ERROR_CODE", 12, 2112, "Policy not applied");
    CAMDO_UPLOAD_NOT_OPTED_ERROR_CODE = new CaMDOError("CAMDO_UPLOAD_NOT_OPTED_ERROR_CODE", 13, 2113, "Upload: Not opted ");
    CAMDO_UPLOAD_INPROGRESS_ERROR_CODE = new CaMDOError("CAMDO_UPLOAD_INPROGRESS_ERROR_CODE", 14, 2114, "Error while upload is in progress");
    CAMDO_INVALID_DATALENGTH_ERROR_CODE = new CaMDOError("CAMDO_INVALID_DATALENGTH_ERROR_CODE", 15, 2115, "Invalid data length");
    CAMDO_JSON_PARSE_ERROR_CODE = new CaMDOError("CAMDO_JSON_PARSE_ERROR_CODE", 16, 2116, "JSON Parsing error");
    CAMDO_TRANSACTION_NOT_PRESENT_ERROR_CODE = new CaMDOError("CAMDO_TRANSACTION_NOT_PRESENT_ERROR_CODE", 17, 2117, "Transaction not found");
    $VALUES = new CaMDOError[] { 
        CAMDO_UNKNOWN_ERROR_CODE, CAMDO_INVALID_PARAMETER_ERROR_CODE, CAMDO_LOG_INITIALIZE_ERROR_CODE, CAMDO_LOG_TEXTMETRIC_ERROR_CODE, CAMDO_LOG_NUMERICMETRIC_ERROR_CODE, CAMDO_LOG_NETWORKMETRIC_ERROR_CODE, CAMDO_LOG_SENDSCREENSHOT_ERROR_CODE, CAMDO_START_TRANSACTION_FAILED_ERROR_CODE, CAMDO_STOP_TRANSACTION_FAILED_ERROR_CODE, CAMDO_UPLOAD_ERROR_CODE, 
        CAMDO_UPLOAD_WIFI_DISABLED_ERROR_CODE, CAMDO_UPLOAD_PERMISSION_DENIED_ERROR_CODE, CAMDO_POLICY_NOT_APPLIED_ERROR_CODE, CAMDO_UPLOAD_NOT_OPTED_ERROR_CODE, CAMDO_UPLOAD_INPROGRESS_ERROR_CODE, CAMDO_INVALID_DATALENGTH_ERROR_CODE, CAMDO_JSON_PARSE_ERROR_CODE, CAMDO_TRANSACTION_NOT_PRESENT_ERROR_CODE };
  }
  
  CaMDOError(int paramInt1, String paramString1) {
    this.code = paramInt1;
    this.message = paramString1;
  }
  
  public int getCode() {
    return this.code;
  }
  
  public String getMessage() {
    return this.message;
  }
  
  public String toString() {
    return this.code + ": " + this.message;
  }
}


/* Location:              C:\Users\devid\Downloads\SAST\Santander\dex2jar-2.0\classes2-dex2jar.jar!\com\ca\mdo\CaMDOError.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */