import android.support.annotation.NonNull;
import java.util.concurrent.TimeUnit;

public final class ddt<R extends cqg> extends cpx<R> {
  private final dat<R> a;
  
  public ddt(cpy<R> paramcpy) {
    if (!(paramcpy instanceof dat))
      throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call."); 
    this.a = (dat<R>)paramcpy;
  }
  
  public R a(long paramLong, TimeUnit paramTimeUnit) {
    return (R)this.a.a(paramLong, paramTimeUnit);
  }
  
  @NonNull
  public <S extends cqg> cqk<S> a(@NonNull cqj<? super R, ? extends S> paramcqj) {
    return this.a.a(paramcqj);
  }
  
  public void a() {
    this.a.a();
  }
  
  public void a(cpz paramcpz) {
    this.a.a(paramcpz);
  }
  
  public void a(cqh<? super R> paramcqh) {
    this.a.a(paramcqh);
  }
  
  public void a(cqh<? super R> paramcqh, long paramLong, TimeUnit paramTimeUnit) {
    this.a.a(paramcqh, paramLong, paramTimeUnit);
  }
  
  public boolean b() {
    return this.a.g();
  }
  
  public R c() {
    if (b())
      return a(0L, TimeUnit.MILLISECONDS); 
    throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
  }
  
  public R d() {
    return (R)this.a.d();
  }
  
  public boolean e() {
    return this.a.e();
  }
  
  public Integer f() {
    return this.a.f();
  }
}


/* Location:              C:\Users\devid\Downloads\SAST\Santander\dex2jar-2.0\classes2-dex2jar.jar!\ddt.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */