public enum eqn {
  BYTE_SEGMENTS, ERROR_CORRECTION_LEVEL, ISSUE_NUMBER, ORIENTATION, OTHER, PDF417_EXTRA_METADATA, POSSIBLE_COUNTRY, STRUCTURED_APPEND_PARITY, STRUCTURED_APPEND_SEQUENCE, SUGGESTED_PRICE, UPC_EAN_EXTENSION;
  
  static {
    ORIENTATION = new eqn("ORIENTATION", 1);
    BYTE_SEGMENTS = new eqn("BYTE_SEGMENTS", 2);
    ERROR_CORRECTION_LEVEL = new eqn("ERROR_CORRECTION_LEVEL", 3);
    ISSUE_NUMBER = new eqn("ISSUE_NUMBER", 4);
    SUGGESTED_PRICE = new eqn("SUGGESTED_PRICE", 5);
    POSSIBLE_COUNTRY = new eqn("POSSIBLE_COUNTRY", 6);
    UPC_EAN_EXTENSION = new eqn("UPC_EAN_EXTENSION", 7);
    PDF417_EXTRA_METADATA = new eqn("PDF417_EXTRA_METADATA", 8);
    STRUCTURED_APPEND_SEQUENCE = new eqn("STRUCTURED_APPEND_SEQUENCE", 9);
    STRUCTURED_APPEND_PARITY = new eqn("STRUCTURED_APPEND_PARITY", 10);
    $VALUES = new eqn[] { 
        OTHER, ORIENTATION, BYTE_SEGMENTS, ERROR_CORRECTION_LEVEL, ISSUE_NUMBER, SUGGESTED_PRICE, POSSIBLE_COUNTRY, UPC_EAN_EXTENSION, PDF417_EXTRA_METADATA, STRUCTURED_APPEND_SEQUENCE, 
        STRUCTURED_APPEND_PARITY };
  }
}


/* Location:              C:\Users\devid\Downloads\SAST\Santander\dex2jar-2.0\classes2-dex2jar.jar!\eqn.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */