public enum jox {
  MENU_CAMPANHA,
  MENU_ITEM_ABRA_SUA_CONTA,
  MENU_ITEM_AGENCIAS,
  MENU_ITEM_AGENDAMENTOS,
  MENU_ITEM_AJUDA,
  MENU_ITEM_CAMBIO,
  MENU_ITEM_CAPITALIZACAO,
  MENU_ITEM_CARTAO_DE_CREDITO,
  MENU_ITEM_CARTEIRA_DIARIA,
  MENU_ITEM_CONTA_CORRIENTE,
  MENU_ITEM_CREDITO_IMOBILIARIO,
  MENU_ITEM_EMPRESTIMOS,
  MENU_ITEM_GESTAO_DE_CREDITO,
  MENU_ITEM_HOME(0, "Home"),
  MENU_ITEM_INVESTIMENTOS(0, "Home"),
  MENU_ITEM_MEU_PERFIL(0, "Home"),
  MENU_ITEM_NOTIFICACOES(0, "Home"),
  MENU_ITEM_PAGAMENTOS(0, "Home"),
  MENU_ITEM_PHOTO(0, "Home"),
  MENU_ITEM_POUPANCA(0, "Home"),
  MENU_ITEM_PROPOSTAS_ABERTO(0, "Home"),
  MENU_ITEM_RECARGAR(0, "Home"),
  MENU_ITEM_RENEGOCIACAO(0, "Home"),
  MENU_ITEM_SAIR(0, "Home"),
  MENU_ITEM_SEGUNDA_VIA_COMPROVANTES(0, "Home"),
  MENU_ITEM_SEGUROS(0, "Home"),
  MENU_ITEM_TRANSFERENCIA(0, "Home"),
  MENU_ITEM_VERMELHINHA(0, "Home"),
  MENU_ITEM_WEBVIEW(0, "Home"),
  MENU_LOJA_ONLINE(0, "Home"),
  SUBMENU_CAD_DEBITO_AUTOMATICO(0, "Home"),
  SUBMENU_DDA(0, "Home"),
  SUBMENU_ESCOLHA_CONTA_PREFERENCIAL(0, "Home"),
  SUBMENU_ID_URA_QR_IB(0, "Home"),
  SUBMENU_ITEM_AJUSTAR_LIMITES(0, "Home"),
  SUBMENU_ITEM_AJUSTAR_LIMITE_DE_CONTA(0, "Home"),
  SUBMENU_ITEM_ANTECIPACAO_DT(0, "Home"),
  SUBMENU_ITEM_ANTECIPACAO_IR(0, "Home"),
  SUBMENU_ITEM_ATIVAR_CSO(0, "Home"),
  SUBMENU_ITEM_BLOQUEIO(0, "Home"),
  SUBMENU_ITEM_CANCELAR_INVESTIMENTO(0, "Home"),
  SUBMENU_ITEM_CHAT(0, "Home"),
  SUBMENU_ITEM_CONFIGURACAO_NOTIFICACAO(0, "Home"),
  SUBMENU_ITEM_CONTATO(0, "Home"),
  SUBMENU_ITEM_CONTRATAR_SEGURO(0, "Home"),
  SUBMENU_ITEM_DESABILITAR_TRANSFERGOLDEN(0, "Home"),
  SUBMENU_ITEM_DESBLOQUEIO(0, "Home"),
  SUBMENU_ITEM_EMAIL_FATURA(0, "Home"),
  SUBMENU_ITEM_EXTRATO(0, "Home"),
  SUBMENU_ITEM_FATURAS(0, "Home"),
  SUBMENU_ITEM_FINGERPRINT(0, "Home"),
  SUBMENU_ITEM_GERAR_CARTAO_VIRTUAL(0, "Home"),
  SUBMENU_ITEM_HABILITAR_OUTRO_DEVICE(0, "Home"),
  SUBMENU_ITEM_HABILITAR_TRANSFERGOLDEN(0, "Home"),
  SUBMENU_ITEM_HAB_CART_EXT(0, "Home"),
  SUBMENU_ITEM_ID_SANTANDER(0, "Home"),
  SUBMENU_ITEM_INVESTIMENTO_FUNDOS(0, "Home"),
  SUBMENU_ITEM_INVESTIMENTO_NO_ATM(0, "Home"),
  SUBMENU_ITEM_INVESTIMENTO_PREVIDENCIA(0, "Home"),
  SUBMENU_ITEM_INVESTIMENTO_RENDA_FIXA(0, "Home"),
  SUBMENU_ITEM_LANCAMENTO_FUTURO(0, "Home"),
  SUBMENU_ITEM_MEUS_COMPROMISSOS(0, "Home"),
  SUBMENU_ITEM_MEUS_EMPRESTIMOS(0, "Home"),
  SUBMENU_ITEM_MEUS_INVESTIMENTOS(0, "Home"),
  SUBMENU_ITEM_MEUS_SEGUROS(0, "Home"),
  SUBMENU_ITEM_MEUS_SINISTROS(0, "Home"),
  SUBMENU_ITEM_MINHAS_ASSISTENCIAS(0, "Home"),
  SUBMENU_ITEM_OPERACOES_SEGUROS(0, "Home"),
  SUBMENU_ITEM_PAGAMENTO_FATURA(0, "Home"),
  SUBMENU_ITEM_PARCELAMENTO_FATURA(0, "Home"),
  SUBMENU_ITEM_POLITICIA_PRIVACIDADE_GOOGLE(0, "Home"),
  SUBMENU_ITEM_PONTOS_ESFERA(0, "Home"),
  SUBMENU_ITEM_RENEGOCIACAO_CANCELAR(0, "Home"),
  SUBMENU_ITEM_RENEGOCIACAO_SIMULAR(0, "Home"),
  SUBMENU_ITEM_SALDO(0, "Home"),
  SUBMENU_ITEM_SIMULAR_CONTRATAR(0, "Home"),
  SUBMENU_ITEM_SINCRONIZAR_ID_SANTANDER(0, "Home"),
  SUBMENU_ITEM_SOLICITAR_CSO(0, "Home"),
  SUBMENU_ITEM_SOLICITE_SEU_CARTAO(0, "Home"),
  SUBMENU_ITEM_TRANSF_EXTERIOR(0, "Home"),
  SUBMENU_ITEM_TROCA_DE_SENHA(0, "Home"),
  SUBMENU_ITEM_ULTIMAS_COMPRAS(0, "Home"),
  SUBMENU_ITEM_WAY(0, "Home"),
  SUBMENU_PGTO_TITULOS_CARTORIOS(0, "Home"),
  SUBMENU_PGTO_TITULOS_CONTAS(0, "Home"),
  SUBMENU_PGTO_TITULOS_PUBLICOS(0, "Home");
  
  private int idx;
  
  private String name;
  
  static {
    MENU_ITEM_CONTA_CORRIENTE = new jox("MENU_ITEM_CONTA_CORRIENTE", 1, 1, "Conta Corrente");
    MENU_ITEM_CARTAO_DE_CREDITO = new jox("MENU_ITEM_CARTAO_DE_CREDITO", 2, 2, "Cartões");
    MENU_ITEM_PAGAMENTOS = new jox("MENU_ITEM_PAGAMENTOS", 3, 3, "Pagamentos");
    MENU_ITEM_TRANSFERENCIA = new jox("MENU_ITEM_TRANSFERENCIA", 4, 4, "Transferências");
    MENU_ITEM_RECARGAR = new jox("MENU_ITEM_RECARGAR", 5, 5, "Recarga de Telefone");
    MENU_ITEM_INVESTIMENTOS = new jox("MENU_ITEM_INVESTIMENTOS", 6, 6, "Investimentos");
    MENU_ITEM_EMPRESTIMOS = new jox("MENU_ITEM_EMPRESTIMOS", 7, 7, "Empréstimos");
    MENU_ITEM_AGENCIAS = new jox("MENU_ITEM_AGENCIAS", 8, 8, "Agências");
    MENU_ITEM_AJUDA = new jox("MENU_ITEM_AJUDA", 9, 9, "Ajuda");
    MENU_ITEM_SAIR = new jox("MENU_ITEM_SAIR", 10, 10, "Sair");
    MENU_ITEM_PHOTO = new jox("MENU_ITEM_PHOTO", 11, 11, "Tirar Foto");
    MENU_ITEM_MEU_PERFIL = new jox("MENU_ITEM_MEU_PERFIL", 12, 13, "Meu Perfil");
    MENU_ITEM_ABRA_SUA_CONTA = new jox("MENU_ITEM_ABRA_SUA_CONTA", 13, 19, "Abra sua Conta");
    MENU_ITEM_POUPANCA = new jox("MENU_ITEM_POUPANCA", 14, 51, "Poupança");
    MENU_ITEM_AGENDAMENTOS = new jox("MENU_ITEM_AGENDAMENTOS", 15, 27, "Agendamentos");
    MENU_ITEM_CAMBIO = new jox("MENU_ITEM_CAMBIO", 16, 42, "Câmbio");
    MENU_ITEM_CARTEIRA_DIARIA = new jox("MENU_ITEM_CARTEIRA_DIARIA", 17, 52, "Carteira Diária");
    MENU_ITEM_SEGUROS = new jox("MENU_ITEM_SEGUROS", 18, 38, "Seguros");
    SUBMENU_ITEM_CONTRATAR_SEGURO = new jox("SUBMENU_ITEM_CONTRATAR_SEGURO", 19, 39, "Contratar Seguro");
    SUBMENU_ITEM_MEUS_SEGUROS = new jox("SUBMENU_ITEM_MEUS_SEGUROS", 20, 40, "Meus Seguros");
    SUBMENU_ITEM_MEUS_SINISTROS = new jox("SUBMENU_ITEM_MEUS_SINISTROS", 21, 41, "Acompanhar Sinistros");
    SUBMENU_ITEM_MINHAS_ASSISTENCIAS = new jox("SUBMENU_ITEM_MINHAS_ASSISTENCIAS", 22, 45, "Acompanhar Assistências");
    SUBMENU_ITEM_CHAT = new jox("SUBMENU_ITEM_CHAT", 23, 42, "Chat");
    SUBMENU_ITEM_CONTATO = new jox("SUBMENU_ITEM_CONTATO", 24, 43, "Contato");
    MENU_ITEM_CREDITO_IMOBILIARIO = new jox("MENU_ITEM_CREDITO_IMOBILIARIO", 25, 44, "Crédito Imobiliário");
    MENU_ITEM_VERMELHINHA = new jox("MENU_ITEM_VERMELHINHA", 26, 61, "Vermelhinha");
    MENU_ITEM_CAPITALIZACAO = new jox("MENU_ITEM_CAPITALIZACAO", 27, 45, "Contrate Capitalização");
    MENU_ITEM_WEBVIEW = new jox("MENU_ITEM_WEBVIEW", 28, 46, "Webview");
    SUBMENU_ITEM_WAY = new jox("SUBMENU_ITEM_WAY", 29, 47, "Conheça o App Way");
    SUBMENU_ITEM_ULTIMAS_COMPRAS = new jox("SUBMENU_ITEM_ULTIMAS_COMPRAS", 30, 50, "Últimas Compras");
    SUBMENU_ITEM_GERAR_CARTAO_VIRTUAL = new jox("SUBMENU_ITEM_GERAR_CARTAO_VIRTUAL", 31, 51, "Gerar Cartão Compra Online");
    SUBMENU_ITEM_PONTOS_ESFERA = new jox("SUBMENU_ITEM_PONTOS_ESFERA", 32, 49, "Pontos Esfera");
    SUBMENU_ITEM_FATURAS = new jox("SUBMENU_ITEM_FATURAS", 33, 14, "Faturas");
    SUBMENU_ITEM_PAGAMENTO_FATURA = new jox("SUBMENU_ITEM_PAGAMENTO_FATURA", 34, 15, "Pagamento de Fatura");
    SUBMENU_ITEM_PARCELAMENTO_FATURA = new jox("SUBMENU_ITEM_PARCELAMENTO_FATURA", 35, 16, "Parcelamento de Fatura");
    SUBMENU_ITEM_EMAIL_FATURA = new jox("SUBMENU_ITEM_EMAIL_FATURA", 36, 17, "Cad. Fatura por Email");
    SUBMENU_ITEM_DESBLOQUEIO = new jox("SUBMENU_ITEM_DESBLOQUEIO", 37, 18, "Desbloqueio");
    SUBMENU_ITEM_BLOQUEIO = new jox("SUBMENU_ITEM_BLOQUEIO", 38, 34, "Bloqueio");
    SUBMENU_ITEM_HAB_CART_EXT = new jox("SUBMENU_ITEM_HAB_CART_EXT", 39, 23, "Habilitação Uso Exterior");
    SUBMENU_PGTO_TITULOS_CONTAS = new jox("SUBMENU_PGTO_TITULOS_CONTAS", 40, 20, "Código de Barras");
    SUBMENU_CAD_DEBITO_AUTOMATICO = new jox("SUBMENU_CAD_DEBITO_AUTOMATICO", 41, 21, "Cad. Débito Automático");
    SUBMENU_PGTO_TITULOS_PUBLICOS = new jox("SUBMENU_PGTO_TITULOS_PUBLICOS", 42, 22, "Pagto. Títulos Públicos");
    SUBMENU_PGTO_TITULOS_CARTORIOS = new jox("SUBMENU_PGTO_TITULOS_CARTORIOS", 43, 24, "Títulos em Cartório");
    SUBMENU_DDA = new jox("SUBMENU_DDA", 44, 61, "DDA - Boletos Eletrônicos");
    SUBMENU_ITEM_SIMULAR_CONTRATAR = new jox("SUBMENU_ITEM_SIMULAR_CONTRATAR", 45, 25, "Simular e Contratar");
    SUBMENU_ITEM_ANTECIPACAO_DT = new jox("SUBMENU_ITEM_ANTECIPACAO_DT", 46, 26, "Antecipação 13º");
    SUBMENU_ITEM_TROCA_DE_SENHA = new jox("SUBMENU_ITEM_TROCA_DE_SENHA", 47, 28, "Trocar Senha");
    SUBMENU_ITEM_SOLICITAR_CSO = new jox("SUBMENU_ITEM_SOLICITAR_CSO", 48, 29, "Solicitar CSO");
    SUBMENU_ITEM_ATIVAR_CSO = new jox("SUBMENU_ITEM_ATIVAR_CSO", 49, 30, "Ativar CSO");
    SUBMENU_ITEM_INVESTIMENTO_NO_ATM = new jox("SUBMENU_ITEM_INVESTIMENTO_NO_ATM", 50, 31, "Investimentos no ATM");
    SUBMENU_ITEM_SINCRONIZAR_ID_SANTANDER = new jox("SUBMENU_ITEM_SINCRONIZAR_ID_SANTANDER", 51, 36, "Sincronizar ID Santander");
    SUBMENU_ITEM_ID_SANTANDER = new jox("SUBMENU_ITEM_ID_SANTANDER", 52, 35, "Habilitar ID Santander");
    SUBMENU_ITEM_HABILITAR_OUTRO_DEVICE = new jox("SUBMENU_ITEM_HABILITAR_OUTRO_DEVICE", 53, 50, "Habilitar outro Celular");
    SUBMENU_ITEM_FINGERPRINT = new jox("SUBMENU_ITEM_FINGERPRINT", 54, 43, "Digital");
    SUBMENU_ITEM_POLITICIA_PRIVACIDADE_GOOGLE = new jox("SUBMENU_ITEM_POLITICIA_PRIVACIDADE_GOOGLE", 55, 48, "Politica de Privacidade Google");
    SUBMENU_ITEM_CONFIGURACAO_NOTIFICACAO = new jox("SUBMENU_ITEM_CONFIGURACAO_NOTIFICACAO", 56, 53, "Config. de Notificações");
    SUBMENU_ITEM_HABILITAR_TRANSFERGOLDEN = new jox("SUBMENU_ITEM_HABILITAR_TRANSFERGOLDEN", 57, 49, "Habilitar Transferência por Mensagem");
    SUBMENU_ITEM_DESABILITAR_TRANSFERGOLDEN = new jox("SUBMENU_ITEM_DESABILITAR_TRANSFERGOLDEN", 58, 50, "Desabilitar Transferência por Mensagem");
    SUBMENU_ITEM_INVESTIMENTO_PREVIDENCIA = new jox("SUBMENU_ITEM_INVESTIMENTO_PREVIDENCIA", 59, 42, "Previdência");
    SUBMENU_ITEM_INVESTIMENTO_RENDA_FIXA = new jox("SUBMENU_ITEM_INVESTIMENTO_RENDA_FIXA", 60, 39, "CDB / LCI");
    SUBMENU_ITEM_INVESTIMENTO_FUNDOS = new jox("SUBMENU_ITEM_INVESTIMENTO_FUNDOS", 61, 37, "Fundos");
    SUBMENU_ITEM_ANTECIPACAO_IR = new jox("SUBMENU_ITEM_ANTECIPACAO_IR", 62, 27, "Antecipação IR");
    MENU_ITEM_RENEGOCIACAO = new jox("MENU_ITEM_RENEGOCIACAO", 63, 34, "Renegociação");
    SUBMENU_ITEM_RENEGOCIACAO_SIMULAR = new jox("SUBMENU_ITEM_RENEGOCIACAO_SIMULAR", 64, 51, "Simular e Contratar");
    SUBMENU_ITEM_RENEGOCIACAO_CANCELAR = new jox("SUBMENU_ITEM_RENEGOCIACAO_CANCELAR", 65, 52, "Cancelamento");
    SUBMENU_ITEM_SOLICITE_SEU_CARTAO = new jox("SUBMENU_ITEM_SOLICITE_SEU_CARTAO", 66, 33, "Solicite seu Cartão");
    SUBMENU_ITEM_MEUS_INVESTIMENTOS = new jox("SUBMENU_ITEM_MEUS_INVESTIMENTOS", 67, 61, "Meus Investimentos");
    SUBMENU_ITEM_CANCELAR_INVESTIMENTO = new jox("SUBMENU_ITEM_CANCELAR_INVESTIMENTO", 68, 62, "Cancelamento de Aplicações");
    SUBMENU_ITEM_TRANSF_EXTERIOR = new jox("SUBMENU_ITEM_TRANSF_EXTERIOR", 69, 40, "Transf. para o Exterior");
    MENU_ITEM_SEGUNDA_VIA_COMPROVANTES = new jox("MENU_ITEM_SEGUNDA_VIA_COMPROVANTES", 70, 41, "Comprovantes");
    MENU_ITEM_NOTIFICACOES = new jox("MENU_ITEM_NOTIFICACOES", 71, 42, "Notificações");
    MENU_ITEM_PROPOSTAS_ABERTO = new jox("MENU_ITEM_PROPOSTAS_ABERTO", 72, 53, "Propostas em Aberto");
    SUBMENU_ITEM_SALDO = new jox("SUBMENU_ITEM_SALDO", 73, 43, "Saldo");
    SUBMENU_ITEM_EXTRATO = new jox("SUBMENU_ITEM_EXTRATO", 74, 44, "Extrato");
    SUBMENU_ITEM_LANCAMENTO_FUTURO = new jox("SUBMENU_ITEM_LANCAMENTO_FUTURO", 75, 45, "Lançamentos Futuros");
    SUBMENU_ITEM_OPERACOES_SEGUROS = new jox("SUBMENU_ITEM_OPERACOES_SEGUROS", 76, 46, "Operações de Seguros");
    SUBMENU_ITEM_MEUS_EMPRESTIMOS = new jox("SUBMENU_ITEM_MEUS_EMPRESTIMOS", 77, 47, "Meus Empréstimos");
    MENU_ITEM_GESTAO_DE_CREDITO = new jox("MENU_ITEM_GESTAO_DE_CREDITO", 78, 58, "Controle Financeiro");
    SUBMENU_ITEM_MEUS_COMPROMISSOS = new jox("SUBMENU_ITEM_MEUS_COMPROMISSOS", 79, 59, "Meus Compromissos");
    SUBMENU_ITEM_AJUSTAR_LIMITES = new jox("SUBMENU_ITEM_AJUSTAR_LIMITES", 80, 64, "Ajustar Limites");
    SUBMENU_ITEM_AJUSTAR_LIMITE_DE_CONTA = new jox("SUBMENU_ITEM_AJUSTAR_LIMITE_DE_CONTA", 81, 65, "Ajustar Limite de Conta");
    MENU_LOJA_ONLINE = new jox("MENU_LOJA_ONLINE", 82, 60, "Loja Online");
    SUBMENU_ESCOLHA_CONTA_PREFERENCIAL = new jox("SUBMENU_ESCOLHA_CONTA_PREFERENCIAL", 83, 61, "Conta Preferencial");
    SUBMENU_ID_URA_QR_IB = new jox("SUBMENU_ID_URA_QR_IB", 84, 62, "Utilizar ID para outro canal");
    MENU_CAMPANHA = new jox("MENU_CAMPANHA", 85, 64, "Ofertas Pra Você");
    $VALUES = new jox[] { 
        MENU_ITEM_HOME, MENU_ITEM_CONTA_CORRIENTE, MENU_ITEM_CARTAO_DE_CREDITO, MENU_ITEM_PAGAMENTOS, MENU_ITEM_TRANSFERENCIA, MENU_ITEM_RECARGAR, MENU_ITEM_INVESTIMENTOS, MENU_ITEM_EMPRESTIMOS, MENU_ITEM_AGENCIAS, MENU_ITEM_AJUDA, 
        MENU_ITEM_SAIR, MENU_ITEM_PHOTO, MENU_ITEM_MEU_PERFIL, MENU_ITEM_ABRA_SUA_CONTA, MENU_ITEM_POUPANCA, MENU_ITEM_AGENDAMENTOS, MENU_ITEM_CAMBIO, MENU_ITEM_CARTEIRA_DIARIA, MENU_ITEM_SEGUROS, SUBMENU_ITEM_CONTRATAR_SEGURO, 
        SUBMENU_ITEM_MEUS_SEGUROS, SUBMENU_ITEM_MEUS_SINISTROS, SUBMENU_ITEM_MINHAS_ASSISTENCIAS, SUBMENU_ITEM_CHAT, SUBMENU_ITEM_CONTATO, MENU_ITEM_CREDITO_IMOBILIARIO, MENU_ITEM_VERMELHINHA, MENU_ITEM_CAPITALIZACAO, MENU_ITEM_WEBVIEW, SUBMENU_ITEM_WAY, 
        SUBMENU_ITEM_ULTIMAS_COMPRAS, SUBMENU_ITEM_GERAR_CARTAO_VIRTUAL, SUBMENU_ITEM_PONTOS_ESFERA, SUBMENU_ITEM_FATURAS, SUBMENU_ITEM_PAGAMENTO_FATURA, SUBMENU_ITEM_PARCELAMENTO_FATURA, SUBMENU_ITEM_EMAIL_FATURA, SUBMENU_ITEM_DESBLOQUEIO, SUBMENU_ITEM_BLOQUEIO, SUBMENU_ITEM_HAB_CART_EXT, 
        SUBMENU_PGTO_TITULOS_CONTAS, SUBMENU_CAD_DEBITO_AUTOMATICO, SUBMENU_PGTO_TITULOS_PUBLICOS, SUBMENU_PGTO_TITULOS_CARTORIOS, SUBMENU_DDA, SUBMENU_ITEM_SIMULAR_CONTRATAR, SUBMENU_ITEM_ANTECIPACAO_DT, SUBMENU_ITEM_TROCA_DE_SENHA, SUBMENU_ITEM_SOLICITAR_CSO, SUBMENU_ITEM_ATIVAR_CSO, 
        SUBMENU_ITEM_INVESTIMENTO_NO_ATM, SUBMENU_ITEM_SINCRONIZAR_ID_SANTANDER, SUBMENU_ITEM_ID_SANTANDER, SUBMENU_ITEM_HABILITAR_OUTRO_DEVICE, SUBMENU_ITEM_FINGERPRINT, SUBMENU_ITEM_POLITICIA_PRIVACIDADE_GOOGLE, SUBMENU_ITEM_CONFIGURACAO_NOTIFICACAO, SUBMENU_ITEM_HABILITAR_TRANSFERGOLDEN, SUBMENU_ITEM_DESABILITAR_TRANSFERGOLDEN, SUBMENU_ITEM_INVESTIMENTO_PREVIDENCIA, 
        SUBMENU_ITEM_INVESTIMENTO_RENDA_FIXA, SUBMENU_ITEM_INVESTIMENTO_FUNDOS, SUBMENU_ITEM_ANTECIPACAO_IR, MENU_ITEM_RENEGOCIACAO, SUBMENU_ITEM_RENEGOCIACAO_SIMULAR, SUBMENU_ITEM_RENEGOCIACAO_CANCELAR, SUBMENU_ITEM_SOLICITE_SEU_CARTAO, SUBMENU_ITEM_MEUS_INVESTIMENTOS, SUBMENU_ITEM_CANCELAR_INVESTIMENTO, SUBMENU_ITEM_TRANSF_EXTERIOR, 
        MENU_ITEM_SEGUNDA_VIA_COMPROVANTES, MENU_ITEM_NOTIFICACOES, MENU_ITEM_PROPOSTAS_ABERTO, SUBMENU_ITEM_SALDO, SUBMENU_ITEM_EXTRATO, SUBMENU_ITEM_LANCAMENTO_FUTURO, SUBMENU_ITEM_OPERACOES_SEGUROS, SUBMENU_ITEM_MEUS_EMPRESTIMOS, MENU_ITEM_GESTAO_DE_CREDITO, SUBMENU_ITEM_MEUS_COMPROMISSOS, 
        SUBMENU_ITEM_AJUSTAR_LIMITES, SUBMENU_ITEM_AJUSTAR_LIMITE_DE_CONTA, MENU_LOJA_ONLINE, SUBMENU_ESCOLHA_CONTA_PREFERENCIAL, SUBMENU_ID_URA_QR_IB, MENU_CAMPANHA };
  }
  
  jox(int paramInt1, String paramString1) {
    this.idx = paramInt1;
    this.name = paramString1;
  }
  
  public int getIdx() {
    return this.idx;
  }
  
  public String getName() {
    return this.name;
  }
}


/* Location:              C:\Users\devid\Downloads\SAST\Santander\dex2jar-2.0\classes2-dex2jar.jar!\jox.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */