public enum nat {
  APARELHO_NAO_HABILITADO, BLOQUEIO_ADM, BLOQUEIO_CLIENTE, BLOQUEIO_CLONAGEM, BLOQUEIO_TENTATIVAS, ERRO_INESPERADO, ID_CANCELADO, ID_NAO_HABILITADO, USUARIO_CONSULTIVO, USUARIO_SEM_SEMENTE, VER_MAIS_TARDE, VER_MENSAGEM_QR, VER_MENSAGEM_SMS;
  
  static {
    APARELHO_NAO_HABILITADO = new nat("APARELHO_NAO_HABILITADO", 1);
    BLOQUEIO_ADM = new nat("BLOQUEIO_ADM", 2);
    BLOQUEIO_TENTATIVAS = new nat("BLOQUEIO_TENTATIVAS", 3);
    ERRO_INESPERADO = new nat("ERRO_INESPERADO", 4);
    USUARIO_CONSULTIVO = new nat("USUARIO_CONSULTIVO", 5);
    ID_CANCELADO = new nat("ID_CANCELADO", 6);
    BLOQUEIO_CLIENTE = new nat("BLOQUEIO_CLIENTE", 7);
    BLOQUEIO_CLONAGEM = new nat("BLOQUEIO_CLONAGEM", 8);
    VER_MENSAGEM_SMS = new nat("VER_MENSAGEM_SMS", 9);
    VER_MAIS_TARDE = new nat("VER_MAIS_TARDE", 10);
    VER_MENSAGEM_QR = new nat("VER_MENSAGEM_QR", 11);
    USUARIO_SEM_SEMENTE = new nat("USUARIO_SEM_SEMENTE", 12);
    $VALUES = new nat[] { 
        ID_NAO_HABILITADO, APARELHO_NAO_HABILITADO, BLOQUEIO_ADM, BLOQUEIO_TENTATIVAS, ERRO_INESPERADO, USUARIO_CONSULTIVO, ID_CANCELADO, BLOQUEIO_CLIENTE, BLOQUEIO_CLONAGEM, VER_MENSAGEM_SMS, 
        VER_MAIS_TARDE, VER_MENSAGEM_QR, USUARIO_SEM_SEMENTE };
  }
}


/* Location:              C:\Users\devid\Downloads\SAST\Santander\dex2jar-2.0\classes2-dex2jar.jar!\nat.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */