@Deprecated
public enum cft {
  ABOVE_CHART_CENTER, ABOVE_CHART_LEFT, ABOVE_CHART_RIGHT, BELOW_CHART_CENTER, BELOW_CHART_LEFT, BELOW_CHART_RIGHT, LEFT_OF_CHART, LEFT_OF_CHART_CENTER, LEFT_OF_CHART_INSIDE, PIECHART_CENTER, RIGHT_OF_CHART, RIGHT_OF_CHART_CENTER, RIGHT_OF_CHART_INSIDE;
  
  static {
    LEFT_OF_CHART = new cft("LEFT_OF_CHART", 3);
    LEFT_OF_CHART_CENTER = new cft("LEFT_OF_CHART_CENTER", 4);
    LEFT_OF_CHART_INSIDE = new cft("LEFT_OF_CHART_INSIDE", 5);
    BELOW_CHART_LEFT = new cft("BELOW_CHART_LEFT", 6);
    BELOW_CHART_RIGHT = new cft("BELOW_CHART_RIGHT", 7);
    BELOW_CHART_CENTER = new cft("BELOW_CHART_CENTER", 8);
    ABOVE_CHART_LEFT = new cft("ABOVE_CHART_LEFT", 9);
    ABOVE_CHART_RIGHT = new cft("ABOVE_CHART_RIGHT", 10);
    ABOVE_CHART_CENTER = new cft("ABOVE_CHART_CENTER", 11);
    PIECHART_CENTER = new cft("PIECHART_CENTER", 12);
    $VALUES = new cft[] { 
        RIGHT_OF_CHART, RIGHT_OF_CHART_CENTER, RIGHT_OF_CHART_INSIDE, LEFT_OF_CHART, LEFT_OF_CHART_CENTER, LEFT_OF_CHART_INSIDE, BELOW_CHART_LEFT, BELOW_CHART_RIGHT, BELOW_CHART_CENTER, ABOVE_CHART_LEFT, 
        ABOVE_CHART_RIGHT, ABOVE_CHART_CENTER, PIECHART_CENTER };
  }
}


/* Location:              C:\Users\devid\Downloads\SAST\Santander\dex2jar-2.0\classes-dex2jar.jar!\cft.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */