package br.com.santander.dynamicauth.enums;

import java.io.Serializable;

public enum DynamicAuthEnum implements Serializable {
  CANCELED_BY_USER,
  CARD_PWD,
  CARD_PWD_CVV,
  CARD_PWD_DOCUMENT,
  CARD_PWD_EXPIRATION,
  CHALLENGE_CODE,
  CODE_CARD_PWD,
  CODE_CSO,
  CODE_IDSANTANDER_OTP,
  CODE_IDSANTANDER_QRCODE,
  CODE_TOKEN_ANTIGO,
  CODE_TOKEN_FISICO,
  CODE_TOKEN_OTICO,
  CODE_TOKEN_SMS,
  CSO_ID,
  CSO_POSICAO,
  CSO_SEQUENCIA,
  ERRO(610),
  ERRO_CSO_SEQUENCE(610),
  ERRO_ID_SANTANDER(610),
  ERRO_OSG_CODE_BLOCKED_DEVICE(610),
  ERRO_OSG_CODE_CHANNEL_NOT_FOUND(610),
  ERRO_OSG_CODE_FLOW_NOT_FOUND(610),
  ERRO_OSG_CODE_IMPLEMENTATION_CONDITION(610),
  ERRO_OSG_CODE_INVALID_AUTHENTICATION(610),
  ERRO_OSG_CODE_INVALID_FIELD(610),
  ERRO_OSG_CODE_INVALID_FIELD_TYPE(610),
  ERRO_OSG_CODE_INVALID_PAREMETER(610),
  ERRO_OSG_CODE_INVALID_REQUISITION(610),
  ERRO_OSG_CODE_NO_ACTIVE_DEVICE(610),
  ERRO_OSG_CODE_NO_AUTHORIZED_DEVICE(610),
  ERRO_OSG_CODE_PARAMETERS_NOT_EQUALS(610),
  ERRO_OSG_CODE_PENULTIMATE_AUTHENTICATION(610),
  ERRO_OSG_CODE_REDIS(610),
  ERRO_OSG_CODE_REQUIRED_FIELD_NOT_FOUND(610),
  ERRO_OSG_CODE_SECURITY_ELEVATION(610),
  ERRO_OSG_CODE_TRANSACTION_CONSULTIVE_NOT_FOUND(610),
  ERRO_OSG_CODE_TRANSACTION_DENIED(610),
  ERRO_OSG_CODE_TRANSACTION_INVALID(610),
  ERRO_OSG_CODE_TRANSACTION_NOT_FOUND(610),
  ERRO_OSG_CODE_UNKNOW(610),
  ERRO_OSG_CODE_UNKNOW_AA(610),
  ERRO_OSG_CODE_UNKNOW_EG(610),
  ERRO_OSG_CODE_UNKNOW_SR(610),
  ERRO_OSG_CODE_UNKNOW_WC(610),
  ERRO_OSG_MSG(610),
  ERRO_SMS_PHISHING(610),
  ERRO_XML_EMPTY(600),
  ERRO_XML_INVALID(600),
  ERRO_XML_PARSER(601),
  ERRO_XML_REPEATED_ENTRY(601),
  FIRST_ATTEMPT(601),
  ID_SANTANDER(601),
  LAST_ATTEMPT(601),
  NEXT_ATTEMPT(601),
  OSG_RESULT_CODE(601),
  SUCCESS_OSG_CODE(601),
  TOKEN_FISICO(601),
  TOKEN_OTICO_CODE(601),
  TOKEN_OTICO_VIDEO(601);
  
  private final int id;
  
  static {
    ERRO_XML_INVALID = new DynamicAuthEnum("ERRO_XML_INVALID", 3, 602);
    ERRO_XML_REPEATED_ENTRY = new DynamicAuthEnum("ERRO_XML_REPEATED_ENTRY", 4, 603);
    ERRO_CSO_SEQUENCE = new DynamicAuthEnum("ERRO_CSO_SEQUENCE", 5, 604);
    CANCELED_BY_USER = new DynamicAuthEnum("CANCELED_BY_USER", 6, 605);
    ERRO_ID_SANTANDER = new DynamicAuthEnum("ERRO_ID_SANTANDER", 7, 606);
    ERRO_SMS_PHISHING = new DynamicAuthEnum("ERRO_SMS_PHISHING", 8, 607);
    CHALLENGE_CODE = new DynamicAuthEnum("CHALLENGE_CODE", 9, 5000);
    OSG_RESULT_CODE = new DynamicAuthEnum("OSG_RESULT_CODE", 10, 9000);
    ERRO_OSG_MSG = new DynamicAuthEnum("ERRO_OSG_MSG", 11, 9001);
    SUCCESS_OSG_CODE = new DynamicAuthEnum("SUCCESS_OSG_CODE", 12, 0);
    ERRO_OSG_CODE_INVALID_AUTHENTICATION = new DynamicAuthEnum("ERRO_OSG_CODE_INVALID_AUTHENTICATION", 13, 74809);
    ERRO_OSG_CODE_PENULTIMATE_AUTHENTICATION = new DynamicAuthEnum("ERRO_OSG_CODE_PENULTIMATE_AUTHENTICATION", 14, 74810);
    ERRO_OSG_CODE_BLOCKED_DEVICE = new DynamicAuthEnum("ERRO_OSG_CODE_BLOCKED_DEVICE", 15, 74811);
    ERRO_OSG_CODE_SECURITY_ELEVATION = new DynamicAuthEnum("ERRO_OSG_CODE_SECURITY_ELEVATION", 16, 74808);
    ERRO_OSG_CODE_REDIS = new DynamicAuthEnum("ERRO_OSG_CODE_REDIS", 17, 74898);
    ERRO_OSG_CODE_UNKNOW = new DynamicAuthEnum("ERRO_OSG_CODE_UNKNOW", 18, 74899);
    ERRO_OSG_CODE_UNKNOW_AA = new DynamicAuthEnum("ERRO_OSG_CODE_UNKNOW_AA", 19, 74894);
    ERRO_OSG_CODE_UNKNOW_EG = new DynamicAuthEnum("ERRO_OSG_CODE_UNKNOW_EG", 20, 74899);
    ERRO_OSG_CODE_UNKNOW_SR = new DynamicAuthEnum("ERRO_OSG_CODE_UNKNOW_SR", 21, 74892);
    ERRO_OSG_CODE_UNKNOW_WC = new DynamicAuthEnum("ERRO_OSG_CODE_UNKNOW_WC", 22, 74891);
    ERRO_OSG_CODE_NO_ACTIVE_DEVICE = new DynamicAuthEnum("ERRO_OSG_CODE_NO_ACTIVE_DEVICE", 23, 74801);
    ERRO_OSG_CODE_NO_AUTHORIZED_DEVICE = new DynamicAuthEnum("ERRO_OSG_CODE_NO_AUTHORIZED_DEVICE", 24, 74802);
    ERRO_OSG_CODE_INVALID_FIELD = new DynamicAuthEnum("ERRO_OSG_CODE_INVALID_FIELD", 25, 74851);
    ERRO_OSG_CODE_INVALID_REQUISITION = new DynamicAuthEnum("ERRO_OSG_CODE_INVALID_REQUISITION", 26, 74853);
    ERRO_OSG_CODE_INVALID_PAREMETER = new DynamicAuthEnum("ERRO_OSG_CODE_INVALID_PAREMETER", 27, 74881);
    ERRO_OSG_CODE_INVALID_FIELD_TYPE = new DynamicAuthEnum("ERRO_OSG_CODE_INVALID_FIELD_TYPE", 28, 74852);
    ERRO_OSG_CODE_REQUIRED_FIELD_NOT_FOUND = new DynamicAuthEnum("ERRO_OSG_CODE_REQUIRED_FIELD_NOT_FOUND", 29, 74850);
    ERRO_OSG_CODE_TRANSACTION_NOT_FOUND = new DynamicAuthEnum("ERRO_OSG_CODE_TRANSACTION_NOT_FOUND", 30, 74854);
    ERRO_OSG_CODE_TRANSACTION_DENIED = new DynamicAuthEnum("ERRO_OSG_CODE_TRANSACTION_DENIED", 31, 74803);
    ERRO_OSG_CODE_TRANSACTION_INVALID = new DynamicAuthEnum("ERRO_OSG_CODE_TRANSACTION_INVALID", 32, 74804);
    ERRO_OSG_CODE_TRANSACTION_CONSULTIVE_NOT_FOUND = new DynamicAuthEnum("ERRO_OSG_CODE_TRANSACTION_CONSULTIVE_NOT_FOUND", 33, 74805);
    ERRO_OSG_CODE_CHANNEL_NOT_FOUND = new DynamicAuthEnum("ERRO_OSG_CODE_CHANNEL_NOT_FOUND", 34, 74854);
    ERRO_OSG_CODE_FLOW_NOT_FOUND = new DynamicAuthEnum("ERRO_OSG_CODE_FLOW_NOT_FOUND", 35, 74882);
    ERRO_OSG_CODE_PARAMETERS_NOT_EQUALS = new DynamicAuthEnum("ERRO_OSG_CODE_PARAMETERS_NOT_EQUALS", 36, 74807);
    ERRO_OSG_CODE_IMPLEMENTATION_CONDITION = new DynamicAuthEnum("ERRO_OSG_CODE_IMPLEMENTATION_CONDITION", 37, 74880);
    CODE_CSO = new DynamicAuthEnum("CODE_CSO", 38, 1);
    CODE_TOKEN_FISICO = new DynamicAuthEnum("CODE_TOKEN_FISICO", 39, 3);
    CODE_TOKEN_ANTIGO = new DynamicAuthEnum("CODE_TOKEN_ANTIGO", 40, 9);
    CODE_TOKEN_SMS = new DynamicAuthEnum("CODE_TOKEN_SMS", 41, 10);
    CODE_IDSANTANDER_OTP = new DynamicAuthEnum("CODE_IDSANTANDER_OTP", 42, 12);
    CODE_IDSANTANDER_QRCODE = new DynamicAuthEnum("CODE_IDSANTANDER_QRCODE", 43, 13);
    CODE_TOKEN_OTICO = new DynamicAuthEnum("CODE_TOKEN_OTICO", 44, 14);
    CODE_CARD_PWD = new DynamicAuthEnum("CODE_CARD_PWD", 45, 30);
    CSO_ID = new DynamicAuthEnum("CSO_ID", 46, 5006);
    CSO_POSICAO = new DynamicAuthEnum("CSO_POSICAO", 47, 5005);
    CSO_SEQUENCIA = new DynamicAuthEnum("CSO_SEQUENCIA", 48, 5004);
    ID_SANTANDER = new DynamicAuthEnum("ID_SANTANDER", 49, 5003);
    CARD_PWD = new DynamicAuthEnum("CARD_PWD", 50, 5030);
    CARD_PWD_CVV = new DynamicAuthEnum("CARD_PWD_CVV", 51, 31);
    CARD_PWD_EXPIRATION = new DynamicAuthEnum("CARD_PWD_EXPIRATION", 52, 32);
    CARD_PWD_DOCUMENT = new DynamicAuthEnum("CARD_PWD_DOCUMENT", 53, 33);
    TOKEN_FISICO = new DynamicAuthEnum("TOKEN_FISICO", 54, 5012);
    TOKEN_OTICO_VIDEO = new DynamicAuthEnum("TOKEN_OTICO_VIDEO", 55, 5031);
    TOKEN_OTICO_CODE = new DynamicAuthEnum("TOKEN_OTICO_CODE", 56, 5032);
    FIRST_ATTEMPT = new DynamicAuthEnum("FIRST_ATTEMPT", 57, -1);
    NEXT_ATTEMPT = new DynamicAuthEnum("NEXT_ATTEMPT", 58, -2);
    LAST_ATTEMPT = new DynamicAuthEnum("LAST_ATTEMPT", 59, -3);
    $VALUES = new DynamicAuthEnum[] { 
        ERRO, ERRO_XML_EMPTY, ERRO_XML_PARSER, ERRO_XML_INVALID, ERRO_XML_REPEATED_ENTRY, ERRO_CSO_SEQUENCE, CANCELED_BY_USER, ERRO_ID_SANTANDER, ERRO_SMS_PHISHING, CHALLENGE_CODE, 
        OSG_RESULT_CODE, ERRO_OSG_MSG, SUCCESS_OSG_CODE, ERRO_OSG_CODE_INVALID_AUTHENTICATION, ERRO_OSG_CODE_PENULTIMATE_AUTHENTICATION, ERRO_OSG_CODE_BLOCKED_DEVICE, ERRO_OSG_CODE_SECURITY_ELEVATION, ERRO_OSG_CODE_REDIS, ERRO_OSG_CODE_UNKNOW, ERRO_OSG_CODE_UNKNOW_AA, 
        ERRO_OSG_CODE_UNKNOW_EG, ERRO_OSG_CODE_UNKNOW_SR, ERRO_OSG_CODE_UNKNOW_WC, ERRO_OSG_CODE_NO_ACTIVE_DEVICE, ERRO_OSG_CODE_NO_AUTHORIZED_DEVICE, ERRO_OSG_CODE_INVALID_FIELD, ERRO_OSG_CODE_INVALID_REQUISITION, ERRO_OSG_CODE_INVALID_PAREMETER, ERRO_OSG_CODE_INVALID_FIELD_TYPE, ERRO_OSG_CODE_REQUIRED_FIELD_NOT_FOUND, 
        ERRO_OSG_CODE_TRANSACTION_NOT_FOUND, ERRO_OSG_CODE_TRANSACTION_DENIED, ERRO_OSG_CODE_TRANSACTION_INVALID, ERRO_OSG_CODE_TRANSACTION_CONSULTIVE_NOT_FOUND, ERRO_OSG_CODE_CHANNEL_NOT_FOUND, ERRO_OSG_CODE_FLOW_NOT_FOUND, ERRO_OSG_CODE_PARAMETERS_NOT_EQUALS, ERRO_OSG_CODE_IMPLEMENTATION_CONDITION, CODE_CSO, CODE_TOKEN_FISICO, 
        CODE_TOKEN_ANTIGO, CODE_TOKEN_SMS, CODE_IDSANTANDER_OTP, CODE_IDSANTANDER_QRCODE, CODE_TOKEN_OTICO, CODE_CARD_PWD, CSO_ID, CSO_POSICAO, CSO_SEQUENCIA, ID_SANTANDER, 
        CARD_PWD, CARD_PWD_CVV, CARD_PWD_EXPIRATION, CARD_PWD_DOCUMENT, TOKEN_FISICO, TOKEN_OTICO_VIDEO, TOKEN_OTICO_CODE, FIRST_ATTEMPT, NEXT_ATTEMPT, LAST_ATTEMPT };
  }
  
  DynamicAuthEnum(int paramInt1) {
    this.id = paramInt1;
  }
  
  public int getValue() {
    return this.id;
  }
  
  public String toString() {
    return String.valueOf(getValue());
  }
}


/* Location:              C:\Users\devid\Downloads\SAST\Santander\dex2jar-2.0\classes-dex2jar.jar!\br\com\santander\dynamicauth\enums\DynamicAuthEnum.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */